### ISSUE TITLE
Redstone Ore Behavior

### ISSUE THREAD

**Issue by Elocity** [Elemend/Vein-Miner-Version-1#4]
Redstone ore changes state to "lit" when mining, which affects the vein mining behavior. After adding the "minecraft:redstone_ore[lit=true]" to the pickaxe blocklist, making all the ores lit first works somewhat well. Btw, awesome plugin you have made!

**Comment by Elemend** [comment]
I'm now getting back into Minecraft and datapacks and such and was wondering what you mean with this. Can you tell me what "pickaxe blocklist" you mean?

**Comment by Elemend** [comment]
Closed because the pack is discontinued.
